package interfaz;

import dominio.*;
import javax.swing.*;

/**
 *
 * @author Fernando Gonzalez (223939) & Facundo San Andrea (258053)
 */

public class VentanaContrato extends javax.swing.JFrame implements Observador {

    public VentanaContrato(Sistema sistema) {
        initComponents();
        setModelo(sistema);
    }

    @Override
    public void actualizar() {
        //Cada vez que el modelo cambie, vuelvo a cargar la lista
        cargarListas();
        ManejadorTema.aplicarTema(this, modelo.isModoOscuro());

    }

    public void setModelo(Sistema nuevoModelo) {
        this.modelo = nuevoModelo;
        modelo.agregarObservador(this);
        actualizar(); // para refrescar datos en pantalla
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JComboBox();
        lblVehiculo = new javax.swing.JLabel();
        txtVehiculo = new javax.swing.JComboBox();
        lblEmpleado = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JComboBox();
        txtValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lstContratos = new javax.swing.JScrollPane();
        lstContrato = new javax.swing.JList();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblCliente.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblCliente.setText("Cliente");
        jPanel1.add(lblCliente);
        lblCliente.setBounds(20, 30, 80, 30);

        txtCliente.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtCliente.setToolTipText("");
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCliente);
        txtCliente.setBounds(110, 30, 230, 30);

        lblVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblVehiculo.setText("Vehiculo");
        jPanel1.add(lblVehiculo);
        lblVehiculo.setBounds(20, 80, 80, 30);

        txtVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtVehiculo.setToolTipText("");
        txtVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(txtVehiculo);
        txtVehiculo.setBounds(110, 80, 230, 30);

        lblEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblEmpleado.setText("Empleado");
        jPanel1.add(lblEmpleado);
        lblEmpleado.setBounds(20, 130, 80, 30);

        txtEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtEmpleado.setToolTipText("");
        txtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmpleado);
        txtEmpleado.setBounds(110, 130, 230, 30);

        txtValor.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jPanel1.add(txtValor);
        txtValor.setBounds(110, 180, 150, 30);

        lblValor.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblValor.setText("Valor");
        jPanel1.add(lblValor);
        lblValor.setBounds(20, 180, 80, 30);

        lstContrato.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lstContrato.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstContrato.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstContratoValueChanged(evt);
            }
        });
        lstContratos.setViewportView(lstContrato);

        jPanel1.add(lstContratos);
        lstContratos.setBounds(370, 20, 400, 220);

        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnRegistrar.setText("Vincular");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(110, 240, 150, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 320);

        setBounds(0, 0, 803, 346);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehiculoActionPerformed

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = (Cliente) txtCliente.getSelectedItem();
        Vehiculo vehiculo = (Vehiculo) txtVehiculo.getSelectedItem();
        Empleado empleado = (Empleado) txtEmpleado.getSelectedItem();

        if (cliente == null || vehiculo == null || empleado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente, vehículo y empleado.", "Datos incorrectos", JOptionPane.WARNING_MESSAGE);

        } else {
            if (modelo.existeContrato(cliente, vehiculo) == -1) {
                int valor;
                try {
                    valor = Integer.parseInt(txtValor.getText());
                    modelo.agregarContrato(modelo.getContratosMaxId() + 1, cliente, vehiculo, empleado, valor);
                    cargarListas();
                    JOptionPane.showMessageDialog(this, "Contrato creado correctamente.", "Contrato creado", JOptionPane.INFORMATION_MESSAGE);

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "El valor del contrato debe ser un numero", "Datos incorrectos", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe un contrato para ese cliente y vehiculo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lstContratoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstContratoValueChanged
        // TODO add your handling code here:
        int pos = lstContrato.getSelectedIndex();
        if (pos != -1) {
            Contrato contrato = modelo.getListaContratos().get(pos);
            txtCliente.setSelectedItem(contrato.getCliente());
            txtEmpleado.setSelectedItem(contrato.getEmpleado());
            txtVehiculo.setSelectedItem(contrato.getVehiculo());
            txtValor.setText("" + contrato.getValor());
        }
    }//GEN-LAST:event_lstContratoValueChanged

    private void cargarListas() {
        txtCliente.removeAllItems();
        txtEmpleado.removeAllItems();
        txtVehiculo.removeAllItems();

        lstContrato.setListData(modelo.getListaContratos().toArray());
        for (Vehiculo v : modelo.getListaVehiculos()) {
            txtVehiculo.addItem(v);
        }
        for (Cliente c : modelo.getListaClientes()) {
            txtCliente.addItem(c);
        }
        for (Empleado e : modelo.getListaEmpleados()) {
            txtEmpleado.addItem(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JList lstContrato;
    private javax.swing.JScrollPane lstContratos;
    private javax.swing.JComboBox txtCliente;
    private javax.swing.JComboBox txtEmpleado;
    private javax.swing.JTextField txtValor;
    private javax.swing.JComboBox txtVehiculo;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
