package interfaz;

import dominio.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.*;

/**
 *
 * @author Fernando Gonzalez (223939) & Facundo San Andrea (258053)
 */

public class VentanaServiciosAdicionales extends javax.swing.JFrame implements Observador {

    /**
     * Creates new form VentanaServiciosAdicionales
     *
     * @param sistema
     */
    public VentanaServiciosAdicionales(Sistema sistema) {
        initComponents();
        setModelo(sistema);
    }

    @Override
    public void actualizar() {
        //Cada vez que el modelo cambie, vuelvo a cargar la lista
        cargarListas();
        ManejadorTema.aplicarTema(this, modelo.isModoOscuro());

    }

    public void setModelo(Sistema nuevoModelo) {
        this.modelo = nuevoModelo;
        modelo.agregarObservador(this);
        actualizar(); // para refrescar datos en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVehiculo = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        cmbServicios = new javax.swing.JComboBox();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblFormato = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        cmbEmpleados = new javax.swing.JComboBox();
        cmbVehiculos = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstServicios = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servicios Adicionales");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblVehiculo.setText("Vehiculo");
        jPanel1.add(lblVehiculo);
        lblVehiculo.setBounds(20, 30, 100, 30);

        lblEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblEmpleado.setText("Empleado");
        jPanel1.add(lblEmpleado);
        lblEmpleado.setBounds(20, 90, 100, 30);

        lblServicio.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblServicio.setText("Servicio");
        jPanel1.add(lblServicio);
        lblServicio.setBounds(20, 220, 80, 30);

        cmbServicios.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cmbServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(cmbServicios);
        cmbServicios.setBounds(120, 220, 260, 40);

        lblFecha.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblFecha.setText("Fecha");
        jPanel1.add(lblFecha);
        lblFecha.setBounds(20, 150, 80, 30);

        txtFecha.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha);
        txtFecha.setBounds(120, 150, 260, 40);

        lblFormato.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblFormato.setText("( dd/MM/aaaa HH:mm )");
        jPanel1.add(lblFormato);
        lblFormato.setBounds(130, 190, 150, 20);

        lblCosto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblCosto.setText("Costo");
        jPanel1.add(lblCosto);
        lblCosto.setBounds(20, 280, 80, 30);

        txtCosto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCosto);
        txtCosto.setBounds(120, 280, 190, 40);

        btnAgregar.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(120, 360, 180, 50);

        cmbEmpleados.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cmbEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEmpleados);
        cmbEmpleados.setBounds(120, 90, 260, 40);

        cmbVehiculos.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cmbVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiculosActionPerformed(evt);
            }
        });
        jPanel1.add(cmbVehiculos);
        cmbVehiculos.setBounds(120, 30, 260, 40);

        lstServicios.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lstServicios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstServiciosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstServicios);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(420, 20, 470, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 430);

        setBounds(0, 0, 903, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String servicio = cmbServicios.getSelectedItem().toString().trim();
        String fecha = txtFecha.getText().trim();
        String costoTxt = txtCosto.getText().trim();
        if (!costoTxt.equals("")) {
            int costo = 0;
            try {
                costo = Integer.parseInt(costoTxt);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio debe ser un número válido", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int posicion1 = cmbVehiculos.getSelectedIndex();
            int posicion2 = cmbEmpleados.getSelectedIndex();
            if (esFormatoValido(fecha)) {
                if (posicion1 != -1) {
                    if (posicion2 != -1) {
                        Empleado empleadoSelecionado = (Empleado) cmbEmpleados.getSelectedItem();
                        Vehiculo vehiculoSelecionado = (Vehiculo) cmbVehiculos.getSelectedItem();
                        modelo.agregarServicioAdicional(vehiculoSelecionado, empleadoSelecionado, servicio, fecha, costo);
                        cargarListas();
                        JOptionPane.showMessageDialog(this, "Servicio Agregado", "Exito", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Selecione un Empleado para continuar", "Error", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Selecione un Vehiculo para continuar", "Error", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese una fecha valida", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Agregue un Precio", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cargarListas() {
        cargarVehiculos();
        cargarEmpleados();
        cargarServicios();
        lstServicios.setListData(modelo.getListaServicios().toArray());
    }

    public static boolean esFormatoValido(String fecha) {
        boolean valido = false;
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        try {
            LocalDateTime.parse(fecha, formato);
            valido = true;
        } catch (DateTimeParseException e) {
        }
        return valido;
    }

    private void cmbServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServiciosActionPerformed

    }//GEN-LAST:event_cmbServiciosActionPerformed
    private void cargarServicios() {
        cmbServicios.removeAllItems();
        cmbServicios.addItem("Lavado");
        cmbServicios.addItem("Cambio de rueda");
        cmbServicios.addItem("Limpieza de tapizado");
        cmbServicios.addItem("Cambio de luces");
        cmbServicios.addItem("Otro");
    }

    private void cargarVehiculos() {
        cmbVehiculos.removeAllItems();
        for (Vehiculo v : modelo.getListaVehiculos()) {
            cmbVehiculos.addItem(v);
        }
    }

    private void cargarEmpleados() {
        cmbEmpleados.removeAllItems(); 
        for (Empleado e : modelo.getListaEmpleados()) {
            cmbEmpleados.addItem(e);
        }
    }

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void cmbEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpleadosActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void cmbVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVehiculosActionPerformed

    private void lstServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstServiciosValueChanged
        int pos = lstServicios.getSelectedIndex();
        if (pos != -1) {
            Servicio serv = modelo.getListaServicios().get(pos);
            cmbVehiculos.setSelectedItem(serv.getVehiculo());
            cmbEmpleados.setSelectedItem(serv.getEmpleado());
            txtFecha.setText(serv.getFecha());
            cmbServicios.setSelectedItem(serv.getServicio());
            txtCosto.setText("" + serv.getValor());
        }
     }//GEN-LAST:event_lstServiciosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox cmbEmpleados;
    private javax.swing.JComboBox cmbServicios;
    private javax.swing.JComboBox cmbVehiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JList lstServicios;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
