package interfaz;

import dominio.*;
import javax.swing.*;

/**
 *
 * @author Fernando Gonzalez (223939) & Facundo San Andrea (258053)
 */

public class VentanaVehiculo extends javax.swing.JFrame implements Observador {

    public VentanaVehiculo(Sistema sistema) {
        initComponents();
        setModelo(sistema);
    }

    @Override
    public void actualizar() {
        //Cada vez que el modelo cambie, vuelvo a cargar la lista
        cargarListas();
        ManejadorTema.aplicarTema(this, modelo.isModoOscuro());

    }

    public void setModelo(Sistema nuevoModelo) {
        this.modelo = nuevoModelo;
        modelo.agregarObservador(this);
        actualizar(); // para refrescar datos en pantalla
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVehiculos = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstVehiculos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Vehiculos");

        jPanelVehiculos.setToolTipText("");
        jPanelVehiculos.setLayout(null);

        lblMatricula.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMatricula.setText("Matricula");
        jPanelVehiculos.add(lblMatricula);
        lblMatricula.setBounds(40, 20, 100, 40);

        txtMatricula.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMatricula.setToolTipText("");
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        jPanelVehiculos.add(txtMatricula);
        txtMatricula.setBounds(140, 20, 170, 40);

        lblMarca.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMarca.setText("Marca");
        jPanelVehiculos.add(lblMarca);
        lblMarca.setBounds(40, 70, 80, 40);

        txtMarca.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        jPanelVehiculos.add(txtMarca);
        txtMarca.setBounds(140, 70, 170, 40);

        lblModelo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblModelo.setText("Modelo");
        jPanelVehiculos.add(lblModelo);
        lblModelo.setBounds(40, 120, 90, 40);

        txtModelo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        jPanelVehiculos.add(txtModelo);
        txtModelo.setBounds(140, 120, 170, 40);

        lblEstado.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblEstado.setText("Estado");
        jPanelVehiculos.add(lblEstado);
        lblEstado.setBounds(40, 170, 80, 40);

        txtEstado.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        jPanelVehiculos.add(txtEstado);
        txtEstado.setBounds(140, 170, 170, 40);

        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanelVehiculos.add(btnRegistrar);
        btnRegistrar.setBounds(140, 230, 150, 40);

        lstVehiculos.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lstVehiculos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstVehiculos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVehiculosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstVehiculos);

        jPanelVehiculos.add(jScrollPane3);
        jScrollPane3.setBounds(360, 20, 290, 190);

        getContentPane().add(jPanelVehiculos, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 693, 321);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (!txtMatricula.getText().trim().equals("")
                && !txtMarca.getText().trim().equals("")
                && !txtModelo.getText().trim().equals("")
                && !txtEstado.getText().trim().equals("")) {
            if (!modelo.existeVehiculo(txtMatricula.getText())) {
                modelo.agregarVehiculo(txtMatricula.getText(), txtMarca.getText(), txtModelo.getText(), txtEstado.getText());
                cargarListas();
                JOptionPane.showMessageDialog(this, "Vehiculo ingresado correctamente.", "Registro", JOptionPane.INFORMATION_MESSAGE);
                txtMatricula.setText("");
                txtMarca.setText("");
                txtModelo.setText("");
                txtEstado.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Este vehiculo ya fue registrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos para registrar este vehiculo.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void lstVehiculosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVehiculosValueChanged
        // TODO add your handling code here:
        int posicion = lstVehiculos.getSelectedIndex();
        if (posicion != -1) {
            modelo.getListaVehiculos().get(posicion);
            txtMatricula.setText(modelo.getListaVehiculos().get(posicion).getMatricula());
            txtMarca.setText(modelo.getListaVehiculos().get(posicion).getMarca());
            txtModelo.setText(modelo.getListaVehiculos().get(posicion).getModelo());
            txtEstado.setText(modelo.getListaVehiculos().get(posicion).getEstado());
        }
    }//GEN-LAST:event_lstVehiculosValueChanged

    private void cargarListas() {
        //cargo el JList a partir del ArrayList de Vehiculos
        lstVehiculos.setListData(modelo.getListaVehiculos().toArray());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanelVehiculos;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JList lstVehiculos;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
