package interfaz;

import dominio.*;
import javax.swing.JOptionPane;
//Para manejar fechas
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Fernando Gonzalez (223939) & Facundo San Andrea (258053)
 */

public class VentanaSalida extends javax.swing.JFrame implements Observador {

    /**
     * Creates new form VentanaEntrada
     */
    public VentanaSalida(Sistema sistema) {
        initComponents();
        setModelo(sistema);
    }

    @Override
    public void actualizar() {
        //Cada vez que el modelo cambie, vuelvo a cargar la lista
        cargarListas();
        ManejadorTema.aplicarTema(this, modelo.isModoOscuro());
    }

    public void setModelo(Sistema nuevoModelo) {
        this.modelo = nuevoModelo;
        modelo.agregarObservador(this);
        actualizar(); // para refrescar datos en pantalla
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVehiculo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVehiculo = new javax.swing.JList();
        lblEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpleado = new javax.swing.JList();
        lblFecha = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblNotas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNotas = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        lblContrato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Salidas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(95, 91, 0, 0);

        lblVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblVehiculo.setText("Vehiculos");
        getContentPane().add(lblVehiculo);
        lblVehiculo.setBounds(20, 20, 140, 30);

        lstVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lstVehiculo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstVehiculo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVehiculoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstVehiculo);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 210, 120);

        lblEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblEmpleado.setText("Empleados");
        getContentPane().add(lblEmpleado);
        lblEmpleado.setBounds(260, 20, 140, 30);

        lstEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lstEmpleado.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstEmpleado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 60, 210, 120);

        lblFecha.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblFecha.setText("Fecha");
        getContentPane().add(lblFecha);
        lblFecha.setBounds(50, 230, 60, 30);

        lblFormato.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblFormato.setText("( dd/MM/aaaa HH:mm )");
        getContentPane().add(lblFormato);
        lblFormato.setBounds(180, 260, 130, 20);

        txtFecha.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha);
        txtFecha.setBounds(120, 230, 260, 30);

        lblNotas.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblNotas.setText("Notas");
        getContentPane().add(lblNotas);
        lblNotas.setBounds(50, 310, 60, 30);

        txtNotas.setColumns(20);
        txtNotas.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtNotas.setRows(5);
        jScrollPane3.setViewportView(txtNotas);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(120, 310, 260, 96);

        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRegistrar.setText("Confirmar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(160, 430, 150, 40);

        lblContrato.setText("  ");
        getContentPane().add(lblContrato);
        lblContrato.setBounds(70, 200, 290, 17);

        setBounds(0, 0, 489, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (!txtFecha.getText().trim().equals("") && !txtNotas.getText().trim().equals("")) {
            if (esFormatoValido(txtFecha.getText())) {
                if (!lstVehiculo.isSelectionEmpty() && lstVehiculo.getSelectedIndex() != -1) {
                    if (!lstEmpleado.isSelectionEmpty() && lstEmpleado.getSelectedIndex() != -1) {
                        int posicion = lstVehiculo.getSelectedIndex();
                        int posicion2 = lstEmpleado.getSelectedIndex();
                        Vehiculo vehiculo = modelo.getListaVehiculosDentro().get(posicion);
                        mov = modelo.getSalidaParaVehiculo(vehiculo);
                        if (mov != null && esFechaSalidaValida(mov.getFechaEntrada(), txtFecha.getText())) {
                            modelo.setSalidaVehiculo(mov.getVehiculo().getMatricula());
                            mov.setFechaSalida(txtFecha.getText());
                            mov.setNotaSalida(txtNotas.getText());
                            mov.setEmpleadoSalida(modelo.getListaEmpleados().get(posicion2));
                            String duracion = calcularDiferenciaHoras(mov.getFechaEntrada(), mov.getFechaSalida());
                            JOptionPane.showMessageDialog(this, "Salida registrada correctamente. Tiempo total: " + duracion, "Salida registrada", JOptionPane.INFORMATION_MESSAGE);
                            txtNotas.setText("");
                            modelo.notificarObservadores();
                        } else {
                            JOptionPane.showMessageDialog(this, "Ingrese una fecha y hora valido para el registro de salida.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Seleccione un empleado para continuar con la registro de salida", "Alerta", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione un vehiculo para continuar con el registro de salida", "Alerta", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese una fecha y hora valido para el registro de salida.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos para continuar con el registro de salida", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lstVehiculoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVehiculoValueChanged
        // TODO add your handling code here:
        int posicion = lstVehiculo.getSelectedIndex();
        if (posicion != -1) {
            boolean tieneContrato = modelo.existeContratoConVehiculo(modelo.getListaVehiculosDentro().get(posicion));
            if (tieneContrato) {
                lblContrato.setText("Este vehiculo tiene contrato!");
            } else {
                lblContrato.setText("");
            }
        }
    }//GEN-LAST:event_lstVehiculoValueChanged

    private void cargarListas() {
        //cargo el JList a partir del ArrayList de Vehiculos
        lstVehiculo.setListData(modelo.getListaVehiculosDentro().toArray());
        lstEmpleado.setListData(modelo.getListaEmpleados().toArray());
    }

    public static boolean esFormatoValido(String fecha) {
        boolean valido = false;
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        try {
            LocalDateTime.parse(fecha, formato);
            valido = true;
        } catch (DateTimeParseException e) {
        }
        return valido;
    }

    public String calcularDiferenciaHoras(String fechaEntrada, String fechaSalida) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String duracion = "";
        try {
            Date entrada = formato.parse(fechaEntrada);
            Date salida = formato.parse(fechaSalida);
            long diferenciaMillis = salida.getTime() - entrada.getTime();
            long horas = diferenciaMillis / (1000 * 60 * 60);
            long minutos = (diferenciaMillis / (1000 * 60)) % 60;
            duracion = horas + ":" + String.format("%02d", minutos);
        } catch (ParseException e) {
        }
        return duracion;
    }

    public static boolean esFechaSalidaValida(String fechaEntrada, String fechaSalida) {
        boolean valido = false;
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        try {
            LocalDateTime entrada = LocalDateTime.parse(fechaEntrada, formato);
            LocalDateTime salida = LocalDateTime.parse(fechaSalida, formato);
            valido = !salida.isBefore(entrada); // true si salida es igual o después de entrada
        } catch (DateTimeParseException e) {
            // si alguna no es válida, devuelve false
        }
        return valido;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JList lstEmpleado;
    private javax.swing.JList lstVehiculo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextArea txtNotas;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
    private Movimiento mov;
}
